name: Build and Test CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install playwright
      run: npx playwright install
    - name: Start Backend
      run: npm run start-be &
    - name: Should wait for backend to start
      run: sleep 10
    - name: Start Frontend
      run: npm run start-fe &
    - name: Should wait for frontend to start
      run: sleep 10
    - name: Run tests
      run: npm run test

  deploy-fe:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID_FE }}
          api-key: ${{ secrets.RENDER_TOKEN }}          

  deploy-be:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID_BE }}
          api-key: ${{ secrets.RENDER_TOKEN }}

      

       


